### ISSUE TITLE
The Chain of Responsibility Pattern

### ISSUE THREAD

**Issue by albvar** [dfinke/dfinke.github.io#16]
Hello Doug - thank you for your contributions
I hope I am posting this in the right place. I really enjoy reading about Patterns and wanted to take this opportunity to use your blog post and adapt a switch statement I had recently used. The pattern below does what I need it to after some tweaking. I wanted to share some observations I made while going down this path.

- Your blog post mentioned `over engineering` and it sure feels like it is. The original code posted below is much simpler and easier to understand. The target audience I tend to work with tends to gravitate more towards administration and would certainly feel like I am doing them a disservice if I were to start using patterns like these in my day to day.
- I thought this was a good exercise and made me realize that the more I learn the less I really know. Thanks for sharing

## Using a switch statement

```powershell
$subFilter = @"
{
    "Protocol": [
        "OTHER",
        "Dispute",
        "Protocol",
        "Externa",
        "Refill"
    ]
}
"@ | ConvertFrom-Json

$data = @"
Type
OTHER
Test
Dispute
"@ | ConvertFrom-Csv

$computedData = ($data | Where Type -ne $null |
  Select-Object @{N='ComputedTypes';E={
    switch ($_.Type.Trim()) {
        {$_ -in $subFilter.Protocol } { 'Protocol'}
        {$_ -in $subFilter.Issue} { 'Issue' }
        {$_ -in $subFilter.Coaching } { 'Coaching' }
        {$_ -in $subFilter.'Knowledge Tool' } { 'Knowledge Tool' }
        Default { "Uncategorized:$_" }
    } }} | Where ComputedTypes -ne $Null
)

$computedData | Group-Object ComputedTypes | Select Count, Name
```

## Using Chain of Responsibility Pattern

```powershell
class Categorizer {
    hidden [Categorizer] $Next

    [Categorizer] RegisterNext([Categorizer] $next) {
        $this.Next = $next
        return $this.Next
    }
 
    [string] IsSatisfiedBy($string, $categories) { return $null }
}

class ProtocolCategorizer : Categorizer {
    [string] IsSatisfiedBy($string, $categories) {
        if ($string -in $categories.Protocol) { return "Protocol" }
        
        return $this.Next.IsSatisfiedBy($string, $categories)
    }
}

class IssueCategorizer : Categorizer {
    [string] IsSatisfiedBy($string, $categories) {
        if ($string -in $categories.Issue) { return "Issue" }
        
        return $this.Next.IsSatisfiedBy($string, $categories)
    }
}

class CoachingCategorizer : Categorizer {
    [string] IsSatisfiedBy($string, $categories) {
        if ($string -in $categories.Coaching) { return "Coaching" }        
        return $this.Next.IsSatisfiedBy($string, $categories)
    }
}

class KnowledgeCategorizer : Categorizer {
    [string] IsSatisfiedBy($string, $categories) {
        if ($string -in $categories.Knowledge) { return "Knowledge Tool" }        
        return $this.Next.IsSatisfiedBy($string, $categories)
    }
}

class PlainStringCategorizer : Categorizer {
    [string] IsSatisfiedBy($string, $categories) {
        return "Uncategorized:$string"
    }
}

class CategorizerChain {

    hidden $top
    hidden static [CategorizerChain] $instance = [CategorizerChain]::new()

    CategorizerChain() {
        $this.top = [ProtocolCategorizer]::new()
        $this.top.
        RegisterNext([IssueCategorizer]::new()).
        RegisterNext([CoachingCategorizer]::new()).
        RegisterNext([KnowledgeCategorizer]::new()).
        RegisterNext([PlainStringCategorizer]::new())
    }

    [string] static Calculate($string, $categories) {
        return [CategorizerChain]::instance.top.IsSatisfiedBy($string, $categories)
    }
}

$categories = @'
{
    "Coaching": [
        "Misdirected",
        "Inappropriate",
        "Clarification",
        "Not Enough Info"
    ]
} 
'@ | ConvertFrom-Json
@("Misdirected", "Inappropriate", "Clarification", "Not Enough Info", "Test", "Test2") | 
  foreach { [CategorizerChain]::Calculate($_, $categories) } | Group-Object
```

```powershell
# Actual Results
Count Name                      Group
----- ----                      -----
    4 Coaching                  {Coaching, Coaching, Coaching, Coaching}
    1 Uncategorized:Test        {Uncategorized:Test}
    1 Uncategorized:Test2       {Uncategorized:Test2}
```

**Comment by dfinke** [comment]
Thanks for the comment @albvar. Yes, the intention of showing this Design Pattern was not to say it should be used in every case. It all depends on the complexity of what you are building.

What was not covered in the blog post is that PowerShell is a dynamic language. That's why I show the pattern using a `Class` in PowerShell.

Design Patterns are concepts that were really well applied to static languages like C++ and C# for example.
Many of the Design Patterns are not needed in PowerShell because it is dynamic, and the same holds true for languages like Python.

There are times I use classes in my scripts/modules and knowing about Patterns helps.

In your example, the switch statement is good. It doesn't do what the `Chain of responsibility` is intended.

Plus, you are right, you need to develop scripts with your team in mind. Using these abstract approaches is not for everyone and not for every solution.

> The "Chain of responsibility" pattern is a [design pattern](http://social.technet.microsoft.com/wiki/contents/articles/13207.software-design-pattern.aspx), used in software engineering, to define the act of passing a piece of data down a chain of processors. Each processor decided whether to deal with the data or pass it straight on. A variation to this is the "tree of responsibility", where each processor can itself also decide which direction to send the data.

**Comment by albvar** [comment]
Thank you for your perspective on this!
